[default.extend-words]
anual = "anual"
doas = "doas"
earch = "earch"
elete = "elete"
fnd = "fnd"
irectory = "irectory"
ist = "ist"
noet = "noet"
odf = "odf"
ommand = "ommand"
ove = "ove"
typ = "typ"
windo = "windo"
wrk = "wrk"

[files]
extend-exclude = ["install.rb","ohmyzsh"]
